apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: nvshmem-alltoall-latency
spec:
  runPolicy:
    cleanPodPolicy: Running
    backoffLimit: 20
  slotsPerWorker: 8
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
          restartPolicy: OnFailure
          containers:
          - image: 855988369404.dkr.ecr.us-west-2.amazonaws.com/changnit-test:gpucomm-v3
            imagePullPolicy: IfNotPresent
            name: nvshmem-alltoall-launcher
            env:
             - name: PATH
               value: $PATH:/opt/amazon/efa/bin:/usr/bin
            command:
            - /opt/amazon/openmpi/bin/mpirun
            - --allow-run-as-root
            - --tag-output
            - -np
            - "8"
            - -N
            - "8"
            - --bind-to
            - none
            - -x
            - PATH
            - -x
            - LD_LIBRARY_PATH
            - -x
            - FI_PROVIDER=efa
            - -x
            - FI_EFA_FORK_SAFE=1
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - NCCL_BUFFSIZE=8388608
            - -x
            - NCCL_P2P_NET_CHUNKSIZE=524288
            - -x
            - NCCL_TUNER_PLUGIN=/opt/aws-ofi-nccl/install/lib/libnccl-ofi-tuner.so
            - --mca
            - pml
            - ^ucx
            - --mca
            - btl
            - tcp,self
            - --mca
            - btl_tcp_if_exclude
            - lo,docker0,veth_def_agent
            - /opt/nvshmem/bin/perftest/device/coll/alltoall_latency
    Worker:
      replicas: 1
      template:
        spec:
          nodeSelector:
            node.kubernetes.io/instance-type: "ml.p5.48xlarge" # hyperpod instance type
          containers:
          - image: 855988369404.dkr.ecr.us-west-2.amazonaws.com/changnit-test:gpucomm-v3
            imagePullPolicy: IfNotPresent
            name: nvshmem-alltoall-worker
            volumeMounts:
            - name: shmem
              mountPath: /dev/shm
            resources:
              limits:
                nvidia.com/gpu: 8
                hugepages-2Mi: 5120Mi
                vpc.amazonaws.com/efa: 32
                memory: 32000Mi
              requests:
                nvidia.com/gpu: 8
                hugepages-2Mi: 5120Mi
                vpc.amazonaws.com/efa: 32
                memory: 32000Mi
          volumes:
          - name: shmem
            hostPath:
              path: /dev/shm
